name: Build/release

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "35 4 * * 0" # WINTER (CST): 10:35PM  Summer (CDT): 11:35PM on SUNDAY
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build.yaml'
      - '*/package.json'
      - '*/app/**'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y imagemagick

      - name: Find and install dependencies
        run: |
          corepack enable
          find . -maxdepth 2 -type f -name "package.json" -print0 | while IFS= read -r -d $'\0' file; do
            cd "$(dirname "$file")"
            echo "Installing dependencies in $(pwd)"
            yarn install --immutable-cache
            echo "-------------------------"
            cd - > /dev/null
          done

      - name: Build/release Electron app
        uses: paneron/action-electron-builder@v1.8.1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # Directory where NPM/Yarn commands should be run (default: ".")
          package_root: ./electron.build
          # Name of the optional NPM build script which is executed before electron-builder (default: "build")
          build_script_name: "build:pre"
